### ISSUE TITLE
[bug] Unable to place order: The shipping method is missing. Select the shipping method and try again.

### ISSUE THREAD

**Issue by wigman** [hyva-themes/magento2-react-checkout#195]
After updating the shipping information (first set it, select shipping method, then change the shipping address), the Shipping method is no longer set on the quote, while the checkout still shows it being selected.
If there is only one shipping method available, it's impossible to re-select it since the checkout state does still have it selected.

If you reload the checkout you can see the shipping method no longer selected.

![image](https://user-images.githubusercontent.com/4800926/136156663-11b75100-b9c1-47ea-b811-14ccadfdfbb0.png)

**Comment by rajeev-k-tomy** [comment]
Closing this issue as it is fixed already and available in the stable release.

**Comment by tuyennn** [comment]
Same issue on hyva-themes/magento2-luma-checkout

**Comment by vidyasagarmukkavili-hbwsl** [comment]
Issue still persistent in Hyva React Checkout. The previous selected state is not retained on reload of the checkout page and graphql query returns `null` for request of `selected_shipping_methods` in turn making the place order button non-functional as it results in the following error -> 

_![imagecheckout](https://user-images.githubusercontent.com/111496554/211249911-7812079b-49b6-4837-8f68-e5b518d71017.png)_
